"""HoneyHive Models - Re-exported from auto-generated Pydantic models.

Usage:
    from honeyhive.models import CreateConfigurationRequest, CreateDatasetRequest
"""

# Re-export all generated Pydantic models
from honeyhive._generated.models import (
    AddDatapointsResponse,
    AddDatapointsToDatasetRequest,
    BatchCreateDatapointsRequest,
    BatchCreateDatapointsResponse,
    CreateConfigurationRequest,
    CreateConfigurationResponse,
    CreateDatapointRequest,
    CreateDatapointResponse,
    CreateDatasetRequest,
    CreateDatasetResponse,
    CreateMetricRequest,
    CreateMetricResponse,
    CreateToolRequest,
    CreateToolResponse,
    DeleteConfigurationResponse,
    DeleteDatapointParams,
    DeleteDatapointResponse,
    DeleteDatasetQuery,
    DeleteDatasetResponse,
    DeleteExperimentRunParams,
    DeleteExperimentRunResponse,
    DeleteMetricQuery,
    DeleteMetricResponse,
    DeleteSessionResponse,
    DeleteToolQuery,
    DeleteToolResponse,
    EventNode,
    GetConfigurationsQuery,
    GetConfigurationsResponse,
    GetDatapointParams,
    GetDatapointResponse,
    GetDatapointsQuery,
    GetDatapointsResponse,
    GetDatasetsQuery,
    GetDatasetsResponse,
    GetExperimentRunCompareEventsQuery,
    GetExperimentRunCompareParams,
    GetExperimentRunCompareQuery,
    GetExperimentRunMetricsQuery,
    GetExperimentRunParams,
    GetExperimentRunResponse,
    GetExperimentRunResultQuery,
    GetExperimentRunsQuery,
    GetExperimentRunsResponse,
    GetExperimentRunsSchemaQuery,
    GetExperimentRunsSchemaResponse,
    GetMetricsQuery,
    GetMetricsResponse,
    GetSessionResponse,
    GetToolsResponse,
    PostExperimentRunRequest,
    PostExperimentRunResponse,
    PutExperimentRunRequest,
    PutExperimentRunResponse,
    RemoveDatapointFromDatasetParams,
    RemoveDatapointResponse,
    RunMetricRequest,
    RunMetricResponse,
    TODOSchema,
    UpdateConfigurationRequest,
    UpdateConfigurationResponse,
    UpdateDatapointParams,
    UpdateDatapointRequest,
    UpdateDatapointResponse,
    UpdateDatasetRequest,
    UpdateDatasetResponse,
    UpdateMetricRequest,
    UpdateMetricResponse,
    UpdateToolRequest,
    UpdateToolResponse,
)

__all__ = [
    # Configuration models
    "CreateConfigurationRequest",
    "CreateConfigurationResponse",
    "DeleteConfigurationResponse",
    "GetConfigurationsQuery",
    "GetConfigurationsResponse",
    "UpdateConfigurationRequest",
    "UpdateConfigurationResponse",
    # Datapoint models
    "BatchCreateDatapointsRequest",
    "BatchCreateDatapointsResponse",
    "CreateDatapointRequest",
    "CreateDatapointResponse",
    "DeleteDatapointParams",
    "DeleteDatapointResponse",
    "GetDatapointParams",
    "GetDatapointResponse",
    "GetDatapointsQuery",
    "GetDatapointsResponse",
    "UpdateDatapointParams",
    "UpdateDatapointRequest",
    "UpdateDatapointResponse",
    # Dataset models
    "AddDatapointsResponse",
    "AddDatapointsToDatasetRequest",
    "CreateDatasetRequest",
    "CreateDatasetResponse",
    "DeleteDatasetQuery",
    "DeleteDatasetResponse",
    "GetDatasetsQuery",
    "GetDatasetsResponse",
    "RemoveDatapointFromDatasetParams",
    "RemoveDatapointResponse",
    "UpdateDatasetRequest",
    "UpdateDatasetResponse",
    # Event models
    "EventNode",
    # Experiment models
    "DeleteExperimentRunParams",
    "DeleteExperimentRunResponse",
    "GetExperimentRunCompareEventsQuery",
    "GetExperimentRunCompareParams",
    "GetExperimentRunCompareQuery",
    "GetExperimentRunMetricsQuery",
    "GetExperimentRunParams",
    "GetExperimentRunResponse",
    "GetExperimentRunResultQuery",
    "GetExperimentRunsQuery",
    "GetExperimentRunsResponse",
    "GetExperimentRunsSchemaQuery",
    "GetExperimentRunsSchemaResponse",
    "PostExperimentRunRequest",
    "PostExperimentRunResponse",
    "PutExperimentRunRequest",
    "PutExperimentRunResponse",
    # Metric models
    "CreateMetricRequest",
    "CreateMetricResponse",
    "DeleteMetricQuery",
    "DeleteMetricResponse",
    "GetMetricsQuery",
    "GetMetricsResponse",
    "RunMetricRequest",
    "RunMetricResponse",
    "UpdateMetricRequest",
    "UpdateMetricResponse",
    # Session models
    "DeleteSessionResponse",
    "GetSessionResponse",
    # Tool models
    "CreateToolRequest",
    "CreateToolResponse",
    "DeleteToolQuery",
    "DeleteToolResponse",
    "GetToolsResponse",
    "UpdateToolRequest",
    "UpdateToolResponse",
    # Other
    "TODOSchema",
]
