# generated by datamodel-codegen:
#   filename:  v1.yaml
#   timestamp: 2025-12-12T19:12:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveInt,
    RootModel,
    confloat,
    conint,
    constr,
)


class Type(Enum):
    LLM = "LLM"
    pipeline = "pipeline"


class CallType(Enum):
    chat = "chat"
    completion = "completion"


class Type1(Enum):
    text = "text"
    json_object = "json_object"


class ResponseFormat(BaseModel):
    type: Type1


class SelectedFunction(BaseModel):
    id: constr(min_length=1)
    name: constr(min_length=1)
    description: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None


class FunctionCallParams(Enum):
    none = "none"
    auto = "auto"
    force = "force"


class TemplateItem(BaseModel):
    role: str
    content: str


class Parameters(BaseModel):
    call_type: CallType
    model: constr(min_length=1)
    hyperparameters: Optional[Dict[str, Any]] = None
    responseFormat: Optional[ResponseFormat] = None
    selectedFunctions: Optional[List[SelectedFunction]] = None
    functionCallParams: Optional[FunctionCallParams] = None
    forceFunction: Optional[Dict[str, Any]] = None
    template: Optional[Union[List[TemplateItem], str]] = None


class EnvEnum(Enum):
    dev = "dev"
    staging = "staging"
    prod = "prod"


class CreateConfigurationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Optional[Type] = "LLM"
    provider: constr(min_length=1)
    parameters: Parameters
    env: Optional[List[EnvEnum]] = None
    tags: Optional[List[str]] = None
    user_properties: Optional[Dict[str, Any]] = None


class Type2(Enum):
    LLM = "LLM"
    pipeline = "pipeline"


class Type3(Enum):
    text = "text"
    json_object = "json_object"


class ResponseFormat1(BaseModel):
    type: Type3


class Parameters1(BaseModel):
    call_type: CallType
    model: constr(min_length=1)
    hyperparameters: Optional[Dict[str, Any]] = None
    responseFormat: Optional[ResponseFormat1] = None
    selectedFunctions: Optional[List[SelectedFunction]] = None
    functionCallParams: Optional[FunctionCallParams] = None
    forceFunction: Optional[Dict[str, Any]] = None
    template: Optional[Union[List[TemplateItem], str]] = None


class UpdateConfigurationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Optional[Type2] = "LLM"
    provider: Optional[constr(min_length=1)] = None
    parameters: Optional[Parameters1] = None
    env: Optional[List[EnvEnum]] = None
    tags: Optional[List[str]] = None
    user_properties: Optional[Dict[str, Any]] = None


class GetConfigurationsQuery(BaseModel):
    name: Optional[str] = None
    env: Optional[str] = None
    tags: Optional[str] = None


class UpdateConfigurationParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configId: constr(min_length=1)


class DeleteConfigurationParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(min_length=1)


class CreateConfigurationResponse(BaseModel):
    acknowledged: bool
    insertedId: constr(min_length=1)


class UpdateConfigurationResponse(BaseModel):
    acknowledged: bool
    modifiedCount: float
    upsertedId: None
    upsertedCount: float
    matchedCount: float


class DeleteConfigurationResponse(BaseModel):
    acknowledged: bool
    deletedCount: float


class Type4(Enum):
    LLM = "LLM"
    pipeline = "pipeline"


class Type5(Enum):
    text = "text"
    json_object = "json_object"


class ResponseFormat2(BaseModel):
    type: Type5


class Parameters2(BaseModel):
    call_type: CallType
    model: constr(min_length=1)
    hyperparameters: Optional[Dict[str, Any]] = None
    responseFormat: Optional[ResponseFormat2] = None
    selectedFunctions: Optional[List[SelectedFunction]] = None
    functionCallParams: Optional[FunctionCallParams] = None
    forceFunction: Optional[Dict[str, Any]] = None
    template: Optional[Union[List[TemplateItem], str]] = None


class GetConfigurationsResponseItem(BaseModel):
    id: constr(min_length=1)
    name: str
    type: Optional[Type4] = "LLM"
    provider: str
    parameters: Parameters2
    env: List[EnvEnum]
    tags: List[str]
    user_properties: Optional[Dict[str, Any]] = None
    created_at: str
    updated_at: Optional[str] = None


class GetConfigurationsResponse(RootModel[List[GetConfigurationsResponseItem]]):
    root: List[GetConfigurationsResponseItem]


class GetDatapointsQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    datapoint_ids: Optional[List[constr(min_length=1)]] = None
    dataset_name: Optional[str] = None


class GetDatapointParams(BaseModel):
    id: constr(min_length=1)


class CreateDatapointRequest1(BaseModel):
    inputs: Optional[Dict[str, Any]] = {}
    history: Optional[List[Dict[str, Any]]] = []
    ground_truth: Optional[Dict[str, Any]] = {}
    metadata: Optional[Dict[str, Any]] = {}
    linked_event: Optional[str] = None
    linked_datasets: Optional[List[constr(min_length=1)]] = []


class CreateDatapointRequestItem(BaseModel):
    inputs: Optional[Dict[str, Any]] = {}
    history: Optional[List[Dict[str, Any]]] = []
    ground_truth: Optional[Dict[str, Any]] = {}
    metadata: Optional[Dict[str, Any]] = {}
    linked_event: Optional[str] = None
    linked_datasets: Optional[List[constr(min_length=1)]] = []


class CreateDatapointRequest(
    RootModel[Union[CreateDatapointRequest1, List[CreateDatapointRequestItem]]]
):
    root: Union[CreateDatapointRequest1, List[CreateDatapointRequestItem]]


class UpdateDatapointRequest(BaseModel):
    inputs: Optional[Dict[str, Any]] = {}
    history: Optional[List[Dict[str, Any]]] = None
    ground_truth: Optional[Dict[str, Any]] = {}
    metadata: Optional[Dict[str, Any]] = {}
    linked_event: Optional[str] = None
    linked_datasets: Optional[List[constr(min_length=1)]] = None


class UpdateDatapointParams(BaseModel):
    datapoint_id: constr(min_length=1)


class DeleteDatapointParams(BaseModel):
    datapoint_id: constr(min_length=1)


class Mapping(BaseModel):
    inputs: Optional[List[str]] = []
    history: Optional[List[str]] = []
    ground_truth: Optional[List[str]] = []


class DateRange(BaseModel):
    field_gte: Optional[str] = Field(None, alias="$gte")
    field_lte: Optional[str] = Field(None, alias="$lte")


class BatchCreateDatapointsRequest(BaseModel):
    events: Optional[List[constr(min_length=1)]] = None
    mapping: Optional[Mapping] = None
    filters: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = None
    dateRange: Optional[DateRange] = None
    checkState: Optional[Dict[str, bool]] = None
    selectAll: Optional[bool] = None
    dataset_id: Optional[constr(min_length=1)] = None


class Datapoint(BaseModel):
    id: constr(min_length=1)
    inputs: Optional[Dict[str, Any]] = {}
    history: List[Dict[str, Any]]
    ground_truth: Optional[Dict[str, Any]] = {}
    metadata: Optional[Dict[str, Any]] = {}
    linked_event: Optional[str] = None
    created_at: str
    updated_at: str
    linked_datasets: Optional[List[str]] = None


class GetDatapointsResponse(BaseModel):
    datapoints: List[Datapoint]


class DatapointItem(BaseModel):
    id: constr(min_length=1)
    inputs: Optional[Dict[str, Any]] = {}
    history: List[Dict[str, Any]]
    ground_truth: Optional[Dict[str, Any]] = {}
    metadata: Optional[Dict[str, Any]] = {}
    linked_event: Optional[str] = None
    created_at: str
    updated_at: str
    linked_datasets: Optional[List[str]] = None


class GetDatapointResponse(BaseModel):
    datapoint: List[DatapointItem]


class Result(BaseModel):
    insertedIds: List[constr(min_length=1)]


class CreateDatapointResponse(BaseModel):
    inserted: bool
    result: Result


class Result1(BaseModel):
    modifiedCount: float


class UpdateDatapointResponse(BaseModel):
    updated: bool
    result: Result1


class DeleteDatapointResponse(BaseModel):
    deleted: bool


class BatchCreateDatapointsResponse(BaseModel):
    inserted: bool
    insertedIds: List[constr(min_length=1)]


class CreateDatasetRequest(BaseModel):
    name: str
    description: Optional[str] = None
    datapoints: Optional[List[constr(min_length=1)]] = []


class UpdateDatasetRequest(BaseModel):
    dataset_id: constr(min_length=1)
    name: Optional[str] = None
    description: Optional[str] = None
    datapoints: Optional[List[constr(min_length=1)]] = None


class GetDatasetsQuery(BaseModel):
    dataset_id: Optional[constr(min_length=1)] = None
    name: Optional[str] = None
    include_datapoints: Optional[Union[bool, str]] = None


class DeleteDatasetQuery(BaseModel):
    dataset_id: constr(min_length=1)


class AddDatapointsToDatasetRequest(BaseModel):
    data: List[Dict[str, Any]] = Field(..., min_length=1)
    mapping: Mapping


class RemoveDatapointFromDatasetParams(BaseModel):
    dataset_id: constr(min_length=1)
    datapoint_id: constr(min_length=1)


class Result2(BaseModel):
    insertedId: constr(min_length=1)


class CreateDatasetResponse(BaseModel):
    inserted: bool
    result: Result2


class Result3(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    datapoints: Optional[List[constr(min_length=1)]] = []
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class UpdateDatasetResponse(BaseModel):
    result: Result3


class Datapoint1(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    datapoints: Optional[List[constr(min_length=1)]] = []
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class GetDatasetsResponse(BaseModel):
    datapoints: List[Datapoint1]


class Result4(BaseModel):
    id: constr(min_length=1)


class DeleteDatasetResponse(BaseModel):
    result: Result4


class AddDatapointsResponse(BaseModel):
    inserted: bool
    datapoint_ids: List[constr(min_length=1)]


class RemoveDatapointResponse(BaseModel):
    dereferenced: bool
    message: str


class Status(Enum):
    pending = "pending"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"
    running = "running"


class PostExperimentRunRequest(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[Status] = "pending"
    metadata: Optional[Dict[str, Any]] = {}
    results: Optional[Dict[str, Any]] = {}
    dataset_id: Optional[str] = None
    event_ids: Optional[List[str]] = []
    configuration: Optional[Dict[str, Any]] = {}
    evaluators: Optional[List] = []
    session_ids: Optional[List[str]] = []
    datapoint_ids: Optional[List[constr(min_length=1)]] = []
    passing_ranges: Optional[Dict[str, Any]] = {}


class PutExperimentRunRequest(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[Status] = "pending"
    metadata: Optional[Dict[str, Any]] = {}
    results: Optional[Dict[str, Any]] = {}
    event_ids: Optional[List[str]] = None
    configuration: Optional[Dict[str, Any]] = {}
    evaluators: Optional[List] = None
    session_ids: Optional[List[str]] = None
    datapoint_ids: Optional[List[constr(min_length=1)]] = None
    passing_ranges: Optional[Dict[str, Any]] = {}


class DateRange1(BaseModel):
    field_gte: Union[str, float] = Field(..., alias="$gte")
    field_lte: Union[str, float] = Field(..., alias="$lte")


class SortBy(Enum):
    created_at = "created_at"
    updated_at = "updated_at"
    name = "name"
    status = "status"


class SortOrder(Enum):
    asc = "asc"
    desc = "desc"


class GetExperimentRunsQuery(BaseModel):
    dataset_id: Optional[constr(min_length=1)] = None
    page: Optional[conint(ge=1)] = 1
    limit: Optional[conint(ge=1, le=100)] = 20
    run_ids: Optional[List[str]] = None
    name: Optional[str] = None
    status: Optional[Status] = "pending"
    dateRange: Optional[Union[str, DateRange1]] = None
    sort_by: Optional[SortBy] = "created_at"
    sort_order: Optional[SortOrder] = "desc"


class GetExperimentRunParams(BaseModel):
    run_id: str


class GetExperimentRunMetricsQuery(BaseModel):
    dateRange: Optional[str] = None
    filters: Optional[Union[str, List]] = None


class GetExperimentRunResultQuery(BaseModel):
    aggregate_function: Optional[str] = "average"
    filters: Optional[Union[str, List]] = None


class GetExperimentRunCompareParams(BaseModel):
    new_run_id: str
    old_run_id: str


class GetExperimentRunCompareQuery(BaseModel):
    aggregate_function: Optional[str] = "average"
    filters: Optional[Union[str, List]] = None


class GetExperimentRunCompareEventsQuery(BaseModel):
    run_id_1: str
    run_id_2: str
    event_name: Optional[str] = None
    event_type: Optional[str] = None
    filter: Optional[Union[str, Dict[str, Any]]] = None
    limit: Optional[conint(le=1000, gt=0)] = 1000
    page: Optional[PositiveInt] = 1


class DeleteExperimentRunParams(BaseModel):
    run_id: str


class GetExperimentRunsSchemaQuery(BaseModel):
    dateRange: Optional[Union[str, DateRange1]] = None
    evaluation_id: Optional[str] = None


class PostExperimentRunResponse(BaseModel):
    evaluation: Optional[Any] = None
    run_id: str


class PutExperimentRunResponse(BaseModel):
    evaluation: Optional[Any] = None
    warning: Optional[str] = None


class Pagination(BaseModel):
    page: conint(ge=1)
    limit: conint(ge=1)
    total: conint(ge=0)
    total_unfiltered: conint(ge=0)
    total_pages: conint(ge=0)
    has_next: bool
    has_prev: bool


class GetExperimentRunsResponse(BaseModel):
    evaluations: List
    pagination: Pagination
    metrics: List[str]


class GetExperimentRunResponse(BaseModel):
    evaluation: Optional[Any] = None


class FieldModel(BaseModel):
    name: str
    event_type: str


class Mapping2(BaseModel):
    field_name: str
    event_type: str


class GetExperimentRunsSchemaResponse(BaseModel):
    fields: List[FieldModel]
    datasets: List[str]
    mappings: Dict[str, List[Mapping2]]


class DeleteExperimentRunResponse(BaseModel):
    id: str
    deleted: bool


class Type6(Enum):
    PYTHON = "PYTHON"
    LLM = "LLM"
    HUMAN = "HUMAN"
    COMPOSITE = "COMPOSITE"


class ReturnType(Enum):
    float = "float"
    boolean = "boolean"
    string = "string"
    categorical = "categorical"


class Threshold(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: Optional[float] = None
    max: Optional[float] = None
    pass_when: Optional[Union[bool, float]] = None
    passing_categories: Optional[List[str]] = Field(None, min_length=1)


class Category(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str
    score: Optional[float] = None


class ChildMetric(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Optional[constr(min_length=1)] = None
    name: str
    weight: float
    scale: Optional[PositiveInt] = None


class Operator(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    contains = "contains"
    not_contains = "not contains"


class Operator1(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    greater_than = "greater than"
    less_than = "less than"


class Operator2(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"


class Operator3(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    after = "after"
    before = "before"


class Type7(Enum):
    string = "string"
    number = "number"
    boolean = "boolean"
    datetime = "datetime"


class FilterArrayItem(BaseModel):
    field: str
    operator: Union[Operator, Operator1, Operator2, Operator3]
    value: Optional[Union[str, float, bool]] = None
    type: Type7


class Filters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filterArray: List[FilterArrayItem]


class CreateMetricRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Type6
    criteria: constr(min_length=1)
    description: Optional[str] = ""
    return_type: Optional[ReturnType] = "float"
    enabled_in_prod: Optional[bool] = False
    needs_ground_truth: Optional[bool] = False
    sampling_percentage: Optional[confloat(ge=0.0, le=100.0)] = 100
    model_provider: Optional[str] = None
    model_name: Optional[str] = None
    scale: Optional[PositiveInt] = None
    threshold: Optional[Threshold] = None
    categories: Optional[List[Category]] = Field(None, min_length=1)
    child_metrics: Optional[List[ChildMetric]] = Field(None, min_length=1)
    filters: Optional[Filters] = {"filterArray": []}


class Type8(Enum):
    PYTHON = "PYTHON"
    LLM = "LLM"
    HUMAN = "HUMAN"
    COMPOSITE = "COMPOSITE"


class Operator4(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    contains = "contains"
    not_contains = "not contains"


class Operator5(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    greater_than = "greater than"
    less_than = "less than"


class Operator6(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"


class Operator7(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    after = "after"
    before = "before"


class Type9(Enum):
    string = "string"
    number = "number"
    boolean = "boolean"
    datetime = "datetime"


class FilterArrayItem1(BaseModel):
    field: str
    operator: Union[Operator4, Operator5, Operator6, Operator7]
    value: Optional[Union[str, float, bool]] = None
    type: Type9


class Filters1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filterArray: List[FilterArrayItem1]


class UpdateMetricRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = None
    type: Optional[Type8] = None
    criteria: Optional[constr(min_length=1)] = None
    description: Optional[str] = ""
    return_type: Optional[ReturnType] = "float"
    enabled_in_prod: Optional[bool] = False
    needs_ground_truth: Optional[bool] = False
    sampling_percentage: Optional[confloat(ge=0.0, le=100.0)] = 100
    model_provider: Optional[str] = None
    model_name: Optional[str] = None
    scale: Optional[PositiveInt] = None
    threshold: Optional[Threshold] = None
    categories: Optional[List[Category]] = Field(None, min_length=1)
    child_metrics: Optional[List[ChildMetric]] = Field(None, min_length=1)
    filters: Optional[Filters1] = {"filterArray": []}
    id: constr(min_length=1)


class GetMetricsQuery(BaseModel):
    type: Optional[str] = None
    id: Optional[constr(min_length=1)] = None


class DeleteMetricQuery(BaseModel):
    metric_id: constr(min_length=1)


class Type10(Enum):
    PYTHON = "PYTHON"
    LLM = "LLM"
    HUMAN = "HUMAN"
    COMPOSITE = "COMPOSITE"


class Operator8(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    contains = "contains"
    not_contains = "not contains"


class Operator9(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    greater_than = "greater than"
    less_than = "less than"


class Operator10(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"


class Operator11(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    after = "after"
    before = "before"


class Type11(Enum):
    string = "string"
    number = "number"
    boolean = "boolean"
    datetime = "datetime"


class FilterArrayItem2(BaseModel):
    field: str
    operator: Union[Operator8, Operator9, Operator10, Operator11]
    value: Optional[Union[str, float, bool]] = None
    type: Type11


class Filters2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filterArray: List[FilterArrayItem2]


class Metric(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Type10
    criteria: constr(min_length=1)
    description: Optional[str] = ""
    return_type: Optional[ReturnType] = "float"
    enabled_in_prod: Optional[bool] = False
    needs_ground_truth: Optional[bool] = False
    sampling_percentage: Optional[confloat(ge=0.0, le=100.0)] = 100
    model_provider: Optional[str] = None
    model_name: Optional[str] = None
    scale: Optional[PositiveInt] = None
    threshold: Optional[Threshold] = None
    categories: Optional[List[Category]] = Field(None, min_length=1)
    child_metrics: Optional[List[ChildMetric]] = Field(None, min_length=1)
    filters: Optional[Filters2] = {"filterArray": []}


class RunMetricRequest(BaseModel):
    metric: Metric
    event: Optional[Any] = None


class Type12(Enum):
    PYTHON = "PYTHON"
    LLM = "LLM"
    HUMAN = "HUMAN"
    COMPOSITE = "COMPOSITE"


class Operator12(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    contains = "contains"
    not_contains = "not contains"


class Operator13(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    greater_than = "greater than"
    less_than = "less than"


class Operator14(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"


class Operator15(Enum):
    exists = "exists"
    not_exists = "not exists"
    is_ = "is"
    is_not = "is not"
    after = "after"
    before = "before"


class Type13(Enum):
    string = "string"
    number = "number"
    boolean = "boolean"
    datetime = "datetime"


class FilterArrayItem3(BaseModel):
    field: str
    operator: Union[Operator12, Operator13, Operator14, Operator15]
    value: Optional[Union[str, float, bool]] = None
    type: Type13


class Filters3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filterArray: List[FilterArrayItem3]


class GetMetricsResponseItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    type: Type12
    criteria: constr(min_length=1)
    description: Optional[str] = ""
    return_type: Optional[ReturnType] = "float"
    enabled_in_prod: Optional[bool] = False
    needs_ground_truth: Optional[bool] = False
    sampling_percentage: Optional[confloat(ge=0.0, le=100.0)] = 100
    model_provider: Optional[str] = None
    model_name: Optional[str] = None
    scale: Optional[PositiveInt] = None
    threshold: Optional[Threshold] = None
    categories: Optional[List[Category]] = Field(None, min_length=1)
    child_metrics: Optional[List[ChildMetric]] = Field(None, min_length=1)
    filters: Optional[Filters3] = {"filterArray": []}
    id: constr(min_length=1)
    created_at: AwareDatetime
    updated_at: Optional[AwareDatetime] = None


class GetMetricsResponse(RootModel[List[GetMetricsResponseItem]]):
    root: List[GetMetricsResponseItem]


class CreateMetricResponse(BaseModel):
    inserted: bool
    metric_id: constr(min_length=1)


class UpdateMetricResponse(BaseModel):
    updated: bool


class DeleteMetricResponse(BaseModel):
    deleted: bool


class RunMetricResponse(RootModel[Any]):
    root: Any


class GetSessionParams(BaseModel):
    session_id: str


class EventType(Enum):
    session = "session"
    model = "model"
    chain = "chain"
    tool = "tool"


class Scope(BaseModel):
    name: Optional[str] = None


class Metadata(BaseModel):
    num_events: Optional[float] = None
    num_model_events: Optional[float] = None
    has_feedback: Optional[bool] = None
    cost: Optional[float] = None
    total_tokens: Optional[float] = None
    prompt_tokens: Optional[float] = None
    completion_tokens: Optional[float] = None
    scope: Optional[Scope] = None


class EventNode(BaseModel):
    event_id: str
    event_type: EventType
    event_name: str
    parent_id: Optional[str] = None
    children: List
    start_time: float
    end_time: float
    duration: float
    metadata: Metadata
    session_id: Optional[str] = None
    children_ids: Optional[List[str]] = None


class GetSessionResponse(BaseModel):
    request: EventNode


class DeleteSessionParams(BaseModel):
    session_id: str


class DeleteSessionResponse(BaseModel):
    success: bool
    deleted: str


class ToolType(Enum):
    function = "function"
    tool = "tool"


class CreateToolRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None


class UpdateToolRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = None
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None
    id: constr(min_length=1)


class DeleteToolQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(min_length=1)


class GetToolsResponseItem(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None
    created_at: str
    updated_at: Optional[str] = None


class GetToolsResponse(RootModel[List[GetToolsResponseItem]]):
    root: List[GetToolsResponseItem]


class Result5(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None
    created_at: str
    updated_at: Optional[str] = None


class CreateToolResponse(BaseModel):
    inserted: bool
    result: Result5


class Result6(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None
    created_at: str
    updated_at: Optional[str] = None


class UpdateToolResponse(BaseModel):
    updated: bool
    result: Result6


class Result7(BaseModel):
    id: constr(min_length=1)
    name: str
    description: Optional[str] = None
    parameters: Optional[Any] = None
    tool_type: Optional[ToolType] = None
    created_at: str
    updated_at: Optional[str] = None


class DeleteToolResponse(BaseModel):
    deleted: bool
    result: Result7


class TODOSchema(BaseModel):
    message: str = Field(
        ..., description="Placeholder - Zod schema not yet implemented"
    )
