# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-12T03:39:06+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SessionStartRequest(BaseModel):
    project: Annotated[
        str, Field(description="Project name associated with the session")
    ]
    session_name: Annotated[str, Field(description="Name of the session")]
    source: Annotated[
        str, Field(description="Source of the session - production, staging, etc")
    ]
    session_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the session, if not set, it will be auto-generated"
        ),
    ] = None
    children_ids: Annotated[
        Optional[List[str]],
        Field(description="Id of events that are nested within the session"),
    ] = None
    config: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Associated configuration for the session"),
    ] = None
    inputs: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Input object passed to the session - user query, text blob, etc"
        ),
    ] = None
    outputs: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Final output of the session - completion, chunks, etc"),
    ] = None
    error: Annotated[
        Optional[str], Field(description="Any error description if session failed")
    ] = None
    duration: Annotated[
        Optional[float], Field(description="How long the session took in milliseconds")
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user properties associated with the session"),
    ] = None
    metrics: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any values computed over the output of the session"),
    ] = None
    feedback: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user feedback provided for the session output"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Any system or application metadata associated with the session"
        ),
    ] = None
    start_time: Annotated[
        Optional[float],
        Field(description="UTC timestamp (in milliseconds) for the session start"),
    ] = None
    end_time: Annotated[
        Optional[int],
        Field(description="UTC timestamp (in milliseconds) for the session end"),
    ] = None


class SessionPropertiesBatch(BaseModel):
    session_name: Annotated[Optional[str], Field(description="Name of the session")] = (
        None
    )
    source: Annotated[
        Optional[str],
        Field(description="Source of the session - production, staging, etc"),
    ] = None
    session_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the session, if not set, it will be auto-generated"
        ),
    ] = None
    config: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Associated configuration for the session"),
    ] = None
    inputs: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Input object passed to the session - user query, text blob, etc"
        ),
    ] = None
    outputs: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Final output of the session - completion, chunks, etc"),
    ] = None
    error: Annotated[
        Optional[str], Field(description="Any error description if session failed")
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user properties associated with the session"),
    ] = None
    metrics: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any values computed over the output of the session"),
    ] = None
    feedback: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user feedback provided for the session output"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Any system or application metadata associated with the session"
        ),
    ] = None


class EventType(StrEnum):
    session = "session"
    model = "model"
    tool = "tool"
    chain = "chain"


class Event(BaseModel):
    project_id: Annotated[
        Optional[str], Field(description="Name of project associated with the event")
    ] = None
    source: Annotated[
        Optional[str],
        Field(description="Source of the event - production, staging, etc"),
    ] = None
    event_name: Annotated[Optional[str], Field(description="Name of the event")] = None
    event_type: Annotated[
        Optional[EventType],
        Field(
            description='Specify whether the event is of "session", "model", "tool" or "chain" type'
        ),
    ] = None
    event_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the event, if not set, it will be auto-generated"
        ),
    ] = None
    session_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the session associated with the event, if not set, it will be auto-generated"
        ),
    ] = None
    parent_id: Annotated[
        Optional[str], Field(description="Id of the parent event if nested")
    ] = None
    children_ids: Annotated[
        Optional[List[str]],
        Field(description="Id of events that are nested within the event"),
    ] = None
    config: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Associated configuration JSON for the event - model name, vector index name, etc"
        ),
    ] = None
    inputs: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Input JSON given to the event - prompt, chunks, etc"),
    ] = None
    outputs: Annotated[
        Optional[Dict[str, Any]], Field(description="Final output JSON of the event")
    ] = None
    error: Annotated[
        Optional[str], Field(description="Any error description if event failed")
    ] = None
    start_time: Annotated[
        Optional[float],
        Field(description="UTC timestamp (in milliseconds) for the event start"),
    ] = None
    end_time: Annotated[
        Optional[int],
        Field(description="UTC timestamp (in milliseconds) for the event end"),
    ] = None
    duration: Annotated[
        Optional[float], Field(description="How long the event took in milliseconds")
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Any system or application metadata associated with the event"
        ),
    ] = None
    feedback: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user feedback provided for the event output"),
    ] = None
    metrics: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any values computed over the output of the event"),
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user properties associated with the event"),
    ] = None


class Operator(StrEnum):
    is_ = "is"
    is_not = "is not"
    contains = "contains"
    not_contains = "not contains"
    greater_than = "greater than"


class Type(StrEnum):
    string = "string"
    number = "number"
    boolean = "boolean"
    id = "id"


class EventFilter(BaseModel):
    field: Annotated[
        Optional[str],
        Field(
            description="The field name that you are filtering by like `metadata.cost`, `inputs.chat_history.0.content`"
        ),
    ] = None
    value: Annotated[
        Optional[str],
        Field(description="The value that you are filtering the field for"),
    ] = None
    operator: Annotated[
        Optional[Operator],
        Field(
            description='The type of filter you are performing - "is", "is not", "contains", "not contains", "greater than"'
        ),
    ] = None
    type: Annotated[
        Optional[Type],
        Field(
            description='The data type you are using - "string", "number", "boolean", "id" (for object ids)'
        ),
    ] = None


class EventType1(StrEnum):
    model = "model"
    tool = "tool"
    chain = "chain"


class CreateEventRequest(BaseModel):
    project: Annotated[str, Field(description="Project associated with the event")]
    source: Annotated[
        str, Field(description="Source of the event - production, staging, etc")
    ]
    event_name: Annotated[str, Field(description="Name of the event")]
    event_type: Annotated[
        EventType1,
        Field(
            description='Specify whether the event is of "model", "tool" or "chain" type'
        ),
    ]
    event_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the event, if not set, it will be auto-generated"
        ),
    ] = None
    session_id: Annotated[
        Optional[str],
        Field(
            description="Unique id of the session associated with the event, if not set, it will be auto-generated"
        ),
    ] = None
    parent_id: Annotated[
        Optional[str], Field(description="Id of the parent event if nested")
    ] = None
    children_ids: Annotated[
        Optional[List[str]],
        Field(description="Id of events that are nested within the event"),
    ] = None
    config: Annotated[
        Dict[str, Any],
        Field(
            description="Associated configuration JSON for the event - model name, vector index name, etc"
        ),
    ]
    inputs: Annotated[
        Dict[str, Any],
        Field(description="Input JSON given to the event - prompt, chunks, etc"),
    ]
    outputs: Annotated[
        Optional[Dict[str, Any]], Field(description="Final output JSON of the event")
    ] = None
    error: Annotated[
        Optional[str], Field(description="Any error description if event failed")
    ] = None
    start_time: Annotated[
        Optional[float],
        Field(description="UTC timestamp (in milliseconds) for the event start"),
    ] = None
    end_time: Annotated[
        Optional[int],
        Field(description="UTC timestamp (in milliseconds) for the event end"),
    ] = None
    duration: Annotated[
        float, Field(description="How long the event took in milliseconds")
    ]
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Any system or application metadata associated with the event"
        ),
    ] = None
    feedback: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user feedback provided for the event output"),
    ] = None
    metrics: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any values computed over the output of the event"),
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any user properties associated with the event"),
    ] = None


class CreateModelEvent(BaseModel):
    project: Annotated[str, Field(description="Project associated with the event")]
    model: Annotated[str, Field(description="Model name")]
    provider: Annotated[str, Field(description="Model provider")]
    messages: Annotated[
        List[Dict[str, Any]], Field(description="Messages passed to the model")
    ]
    response: Annotated[
        Dict[str, Any], Field(description="Final output JSON of the event")
    ]
    duration: Annotated[
        float, Field(description="How long the event took in milliseconds")
    ]
    usage: Annotated[Dict[str, Any], Field(description="Usage statistics of the model")]
    cost: Annotated[
        Optional[float], Field(description="Cost of the model completion")
    ] = None
    error: Annotated[
        Optional[str], Field(description="Any error description if event failed")
    ] = None
    source: Annotated[
        Optional[str],
        Field(description="Source of the event - production, staging, etc"),
    ] = None
    event_name: Annotated[Optional[str], Field(description="Name of the event")] = None
    hyperparameters: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Hyperparameters used for the model"),
    ] = None
    template: Annotated[
        Optional[List[Dict[str, Any]]], Field(description="Template used for the model")
    ] = None
    template_inputs: Annotated[
        Optional[Dict[str, Any]], Field(description="Inputs for the template")
    ] = None
    tools: Annotated[
        Optional[List[Dict[str, Any]]], Field(description="Tools used for the model")
    ] = None
    tool_choice: Annotated[
        Optional[str], Field(description="Tool choice for the model")
    ] = None
    response_format: Annotated[
        Optional[Dict[str, Any]], Field(description="Response format for the model")
    ] = None


class Type1(StrEnum):
    PYTHON = "PYTHON"
    LLM = "LLM"
    HUMAN = "HUMAN"
    COMPOSITE = "COMPOSITE"


class ReturnType(StrEnum):
    boolean = "boolean"
    float = "float"
    string = "string"
    categorical = "categorical"


class Threshold(BaseModel):
    min: Optional[float] = None
    max: Optional[float] = None
    pass_when: Optional[Union[bool, float]] = None
    passing_categories: Optional[List[str]] = None


class Metric(BaseModel):
    name: Annotated[str, Field(description="Name of the metric")]
    type: Annotated[
        Type1,
        Field(
            description='Type of the metric - "PYTHON", "LLM", "HUMAN" or "COMPOSITE"'
        ),
    ]
    criteria: Annotated[
        str, Field(description="Criteria, code, or prompt for the metric")
    ]
    description: Annotated[
        Optional[str], Field(description="Short description of what the metric does")
    ] = None
    return_type: Annotated[
        Optional[ReturnType],
        Field(
            description='The data type of the metric value - "boolean", "float", "string", "categorical"'
        ),
    ] = None
    enabled_in_prod: Annotated[
        Optional[bool],
        Field(description="Whether to compute on all production events automatically"),
    ] = None
    needs_ground_truth: Annotated[
        Optional[bool],
        Field(description="Whether a ground truth is required to compute it"),
    ] = None
    sampling_percentage: Annotated[
        Optional[int], Field(description="Percentage of events to sample (0-100)")
    ] = None
    model_provider: Annotated[
        Optional[str],
        Field(description="Provider of the model (required for LLM metrics)"),
    ] = None
    model_name: Annotated[
        Optional[str], Field(description="Name of the model (required for LLM metrics)")
    ] = None
    scale: Annotated[
        Optional[int], Field(description="Scale for numeric return types")
    ] = None
    threshold: Annotated[
        Optional[Threshold],
        Field(description="Threshold for deciding passing or failing in tests"),
    ] = None
    categories: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Categories for categorical return type"),
    ] = None
    child_metrics: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Child metrics for composite metrics"),
    ] = None
    filters: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Event filters for when to apply this metric"),
    ] = None
    id: Annotated[Optional[str], Field(description="Unique identifier")] = None
    created_at: Annotated[
        Optional[str], Field(description="Timestamp when metric was created")
    ] = None
    updated_at: Annotated[
        Optional[str], Field(description="Timestamp when metric was last updated")
    ] = None


class MetricEdit(BaseModel):
    metric_id: Annotated[str, Field(description="Unique identifier of the metric")]
    name: Annotated[Optional[str], Field(description="Updated name of the metric")] = (
        None
    )
    type: Annotated[
        Optional[Type1],
        Field(
            description='Type of the metric - "PYTHON", "LLM", "HUMAN" or "COMPOSITE"'
        ),
    ] = None
    criteria: Annotated[
        Optional[str], Field(description="Criteria, code, or prompt for the metric")
    ] = None
    code_snippet: Annotated[
        Optional[str],
        Field(description="Updated code block for the metric (alias for criteria)"),
    ] = None
    description: Annotated[
        Optional[str], Field(description="Short description of what the metric does")
    ] = None
    return_type: Annotated[
        Optional[ReturnType],
        Field(
            description='The data type of the metric value - "boolean", "float", "string", "categorical"'
        ),
    ] = None
    enabled_in_prod: Annotated[
        Optional[bool],
        Field(description="Whether to compute on all production events automatically"),
    ] = None
    needs_ground_truth: Annotated[
        Optional[bool],
        Field(description="Whether a ground truth is required to compute it"),
    ] = None
    sampling_percentage: Annotated[
        Optional[int], Field(description="Percentage of events to sample (0-100)")
    ] = None
    model_provider: Annotated[
        Optional[str],
        Field(description="Provider of the model (required for LLM metrics)"),
    ] = None
    model_name: Annotated[
        Optional[str], Field(description="Name of the model (required for LLM metrics)")
    ] = None
    scale: Annotated[
        Optional[int], Field(description="Scale for numeric return types")
    ] = None
    threshold: Annotated[
        Optional[Threshold],
        Field(description="Threshold for deciding passing or failing in tests"),
    ] = None
    categories: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Categories for categorical return type"),
    ] = None
    child_metrics: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Child metrics for composite metrics"),
    ] = None
    filters: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Event filters for when to apply this metric"),
    ] = None


class ToolType(StrEnum):
    function = "function"
    tool = "tool"


class Tool(BaseModel):
    field_id: Annotated[Optional[str], Field(alias="_id")] = None
    task: Annotated[
        str, Field(description="Name of the project associated with this tool")
    ]
    name: str
    description: Optional[str] = None
    parameters: Annotated[
        Dict[str, Any],
        Field(description="These can be function call params or plugin call params"),
    ]
    tool_type: ToolType


class Type3(StrEnum):
    function = "function"
    tool = "tool"


class CreateToolRequest(BaseModel):
    task: Annotated[
        str, Field(description="Name of the project associated with this tool")
    ]
    name: str
    description: Optional[str] = None
    parameters: Annotated[
        Dict[str, Any],
        Field(description="These can be function call params or plugin call params"),
    ]
    type: Type3


class UpdateToolRequest(BaseModel):
    id: str
    name: str
    description: Optional[str] = None
    parameters: Dict[str, Any]


class Datapoint(BaseModel):
    field_id: Annotated[
        Optional[str], Field(alias="_id", description="UUID for the datapoint")
    ] = None
    tenant: Optional[str] = None
    project_id: Annotated[
        Optional[str],
        Field(description="UUID for the project where the datapoint is stored"),
    ] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    inputs: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Arbitrary JSON object containing the inputs for the datapoint"
        ),
    ] = None
    history: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Conversation history associated with the datapoint"),
    ] = None
    ground_truth: Optional[Dict[str, Any]] = None
    linked_event: Annotated[
        Optional[str],
        Field(
            description="Event id for the event from which the datapoint was created"
        ),
    ] = None
    linked_evals: Annotated[
        Optional[List[str]],
        Field(description="Ids of evaluations where the datapoint is included"),
    ] = None
    linked_datasets: Annotated[
        Optional[List[str]],
        Field(description="Ids of all datasets that include the datapoint"),
    ] = None
    saved: Optional[bool] = None
    type: Annotated[
        Optional[str], Field(description="session or event - specify the type of data")
    ] = None
    metadata: Optional[Dict[str, Any]] = None


class CreateDatapointRequest(BaseModel):
    project: Annotated[
        str, Field(description="Name for the project to which the datapoint belongs")
    ]
    inputs: Annotated[
        Dict[str, Any],
        Field(
            description="Arbitrary JSON object containing the inputs for the datapoint"
        ),
    ]
    history: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Conversation history associated with the datapoint"),
    ] = None
    ground_truth: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Expected output JSON object for the datapoint"),
    ] = None
    linked_event: Annotated[
        Optional[str],
        Field(
            description="Event id for the event from which the datapoint was created"
        ),
    ] = None
    linked_datasets: Annotated[
        Optional[List[str]],
        Field(description="Ids of all datasets that include the datapoint"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any additional metadata for the datapoint"),
    ] = None


class UpdateDatapointRequest(BaseModel):
    inputs: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="Arbitrary JSON object containing the inputs for the datapoint"
        ),
    ] = None
    history: Annotated[
        Optional[List[Dict[str, Any]]],
        Field(description="Conversation history associated with the datapoint"),
    ] = None
    ground_truth: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Expected output JSON object for the datapoint"),
    ] = None
    linked_evals: Annotated[
        Optional[List[str]],
        Field(description="Ids of evaluations where the datapoint is included"),
    ] = None
    linked_datasets: Annotated[
        Optional[List[str]],
        Field(description="Ids of all datasets that include the datapoint"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any additional metadata for the datapoint"),
    ] = None


class Type4(StrEnum):
    evaluation = "evaluation"
    fine_tuning = "fine-tuning"


class PipelineType(StrEnum):
    event = "event"
    session = "session"


class CreateDatasetRequest(BaseModel):
    project: Annotated[
        str,
        Field(
            description="Name of the project associated with this dataset like `New Project`"
        ),
    ]
    name: Annotated[str, Field(description="Name of the dataset")]
    description: Annotated[
        Optional[str], Field(description="A description for the dataset")
    ] = None
    type: Annotated[
        Optional[Type4],
        Field(
            description='What the dataset is to be used for - "evaluation" (default) or "fine-tuning"'
        ),
    ] = None
    datapoints: Annotated[
        Optional[List[str]],
        Field(
            description="List of unique datapoint ids to be included in this dataset"
        ),
    ] = None
    linked_evals: Annotated[
        Optional[List[str]],
        Field(
            description="List of unique evaluation run ids to be associated with this dataset"
        ),
    ] = None
    saved: Optional[bool] = None
    pipeline_type: Annotated[
        Optional[PipelineType],
        Field(
            description='The type of data included in the dataset - "event" (default) or "session"'
        ),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any helpful metadata to track for the dataset"),
    ] = None


class Dataset(BaseModel):
    dataset_id: Annotated[
        Optional[str],
        Field(description="Unique identifier of the dataset (alias for id)"),
    ] = None
    project: Annotated[
        Optional[str],
        Field(description="UUID of the project associated with this dataset"),
    ] = None
    name: Annotated[Optional[str], Field(description="Name of the dataset")] = None
    description: Annotated[
        Optional[str], Field(description="A description for the dataset")
    ] = None
    type: Annotated[
        Optional[Type4],
        Field(
            description='What the dataset is to be used for - "evaluation" or "fine-tuning"'
        ),
    ] = None
    datapoints: Annotated[
        Optional[List[str]],
        Field(
            description="List of unique datapoint ids to be included in this dataset"
        ),
    ] = None
    num_points: Annotated[
        Optional[int], Field(description="Number of datapoints included in the dataset")
    ] = None
    linked_evals: Optional[List[str]] = None
    saved: Annotated[
        Optional[bool],
        Field(description="Whether the dataset has been saved or detected"),
    ] = None
    pipeline_type: Annotated[
        Optional[PipelineType],
        Field(
            description='The type of data included in the dataset - "event" (default) or "session"'
        ),
    ] = None
    created_at: Annotated[
        Optional[str], Field(description="Timestamp of when the dataset was created")
    ] = None
    updated_at: Annotated[
        Optional[str],
        Field(description="Timestamp of when the dataset was last updated"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Any helpful metadata to track for the dataset"),
    ] = None


class DatasetUpdate(BaseModel):
    dataset_id: Annotated[
        str, Field(description="The unique identifier of the dataset being updated")
    ]
    name: Annotated[
        Optional[str], Field(description="Updated name for the dataset")
    ] = None
    description: Annotated[
        Optional[str], Field(description="Updated description for the dataset")
    ] = None
    datapoints: Annotated[
        Optional[List[str]],
        Field(
            description="Updated list of datapoint ids for the dataset - note the full list is needed"
        ),
    ] = None
    linked_evals: Annotated[
        Optional[List[str]],
        Field(
            description="Updated list of unique evaluation run ids to be associated with this dataset"
        ),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Updated metadata to track for the dataset"),
    ] = None


class CreateProjectRequest(BaseModel):
    name: str
    description: Optional[str] = None


class UpdateProjectRequest(BaseModel):
    project_id: str
    name: Optional[str] = None
    description: Optional[str] = None


class Project(BaseModel):
    id: Optional[str] = None
    name: str
    description: str


class Status(StrEnum):
    pending = "pending"
    completed = "completed"


class UpdateRunResponse(BaseModel):
    evaluation: Annotated[
        Optional[Dict[str, Any]], Field(description="Database update success message")
    ] = None
    warning: Annotated[
        Optional[str],
        Field(
            description="A warning message if the logged events don't have an associated datapoint id on the event metadata"
        ),
    ] = None


class Datapoints(BaseModel):
    passed: Optional[List[str]] = None
    failed: Optional[List[str]] = None


class Detail(BaseModel):
    metric_name: Optional[str] = None
    metric_type: Optional[str] = None
    event_name: Optional[str] = None
    event_type: Optional[str] = None
    aggregate: Optional[float] = None
    values: Optional[List[Union[float, bool]]] = None
    datapoints: Optional[Datapoints] = None


class Metrics(BaseModel):
    aggregation_function: Optional[str] = None
    details: Optional[List[Detail]] = None


class Metric1(BaseModel):
    name: Optional[str] = None
    event_name: Optional[str] = None
    event_type: Optional[str] = None
    value: Optional[Union[float, bool]] = None
    passed: Optional[bool] = None


class Datapoint1(BaseModel):
    datapoint_id: Optional[str] = None
    session_id: Optional[str] = None
    passed: Optional[bool] = None
    metrics: Optional[List[Metric1]] = None


class ExperimentResultResponse(BaseModel):
    status: Optional[str] = None
    success: Optional[bool] = None
    passed: Optional[List[str]] = None
    failed: Optional[List[str]] = None
    metrics: Optional[Metrics] = None
    datapoints: Optional[List[Datapoint1]] = None


class Metric2(BaseModel):
    metric_name: Optional[str] = None
    event_name: Optional[str] = None
    metric_type: Optional[str] = None
    event_type: Optional[str] = None
    old_aggregate: Optional[float] = None
    new_aggregate: Optional[float] = None
    found_count: Optional[int] = None
    improved_count: Optional[int] = None
    degraded_count: Optional[int] = None
    same_count: Optional[int] = None
    improved: Optional[List[str]] = None
    degraded: Optional[List[str]] = None
    same: Optional[List[str]] = None
    old_values: Optional[List[Union[float, bool]]] = None
    new_values: Optional[List[Union[float, bool]]] = None


class EventDetail(BaseModel):
    event_name: Optional[str] = None
    event_type: Optional[str] = None
    presence: Optional[str] = None


class OldRun(BaseModel):
    field_id: Annotated[Optional[str], Field(alias="_id")] = None
    run_id: Optional[str] = None
    project: Optional[str] = None
    tenant: Optional[str] = None
    created_at: Optional[AwareDatetime] = None
    event_ids: Optional[List[str]] = None
    session_ids: Optional[List[str]] = None
    dataset_id: Optional[str] = None
    datapoint_ids: Optional[List[str]] = None
    evaluators: Optional[List[Dict[str, Any]]] = None
    results: Optional[Dict[str, Any]] = None
    configuration: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    passing_ranges: Optional[Dict[str, Any]] = None
    status: Optional[str] = None
    name: Optional[str] = None


class NewRun(BaseModel):
    field_id: Annotated[Optional[str], Field(alias="_id")] = None
    run_id: Optional[str] = None
    project: Optional[str] = None
    tenant: Optional[str] = None
    created_at: Optional[AwareDatetime] = None
    event_ids: Optional[List[str]] = None
    session_ids: Optional[List[str]] = None
    dataset_id: Optional[str] = None
    datapoint_ids: Optional[List[str]] = None
    evaluators: Optional[List[Dict[str, Any]]] = None
    results: Optional[Dict[str, Any]] = None
    configuration: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    passing_ranges: Optional[Dict[str, Any]] = None
    status: Optional[str] = None
    name: Optional[str] = None


class ExperimentComparisonResponse(BaseModel):
    metrics: Optional[List[Metric2]] = None
    commonDatapoints: Optional[List[str]] = None
    event_details: Optional[List[EventDetail]] = None
    old_run: Optional[OldRun] = None
    new_run: Optional[NewRun] = None


class UUIDType(RootModel[UUID]):
    root: UUID


class EnvEnum(StrEnum):
    dev = "dev"
    staging = "staging"
    prod = "prod"


class CallType(StrEnum):
    chat = "chat"
    completion = "completion"


class SelectedFunction(BaseModel):
    id: Annotated[Optional[str], Field(description="UUID of the function")] = None
    name: Annotated[Optional[str], Field(description="Name of the function")] = None
    description: Annotated[
        Optional[str], Field(description="Description of the function")
    ] = None
    parameters: Annotated[
        Optional[Dict[str, Any]], Field(description="Parameters for the function")
    ] = None


class FunctionCallParams(StrEnum):
    none = "none"
    auto = "auto"
    force = "force"


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    call_type: Annotated[
        CallType, Field(description='Type of API calling - "chat" or "completion"')
    ]
    model: Annotated[str, Field(description="Model unique name")]
    hyperparameters: Annotated[
        Optional[Dict[str, Any]], Field(description="Model-specific hyperparameters")
    ] = None
    responseFormat: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description='Response format for the model with the key "type" and value "text" or "json_object"'
        ),
    ] = None
    selectedFunctions: Annotated[
        Optional[List[SelectedFunction]],
        Field(
            description="List of functions to be called by the model, refer to OpenAI schema for more details"
        ),
    ] = None
    functionCallParams: Annotated[
        Optional[FunctionCallParams],
        Field(description='Function calling mode - "none", "auto" or "force"'),
    ] = None
    forceFunction: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Force function-specific parameters"),
    ] = None


class Type6(StrEnum):
    LLM = "LLM"
    pipeline = "pipeline"


class Configuration(BaseModel):
    field_id: Annotated[
        Optional[str], Field(alias="_id", description="ID of the configuration")
    ] = None
    project: Annotated[
        str, Field(description="ID of the project to which this configuration belongs")
    ]
    name: Annotated[str, Field(description="Name of the configuration")]
    env: Annotated[
        Optional[List[EnvEnum]],
        Field(description="List of environments where the configuration is active"),
    ] = None
    provider: Annotated[
        str, Field(description='Name of the provider - "openai", "anthropic", etc.')
    ]
    parameters: Parameters
    type: Annotated[
        Optional[Type6],
        Field(
            description='Type of the configuration - "LLM" or "pipeline" - "LLM" by default'
        ),
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Details of user who created the configuration"),
    ] = None


class Parameters1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    call_type: Annotated[
        CallType, Field(description='Type of API calling - "chat" or "completion"')
    ]
    model: Annotated[str, Field(description="Model unique name")]
    hyperparameters: Annotated[
        Optional[Dict[str, Any]], Field(description="Model-specific hyperparameters")
    ] = None
    responseFormat: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description='Response format for the model with the key "type" and value "text" or "json_object"'
        ),
    ] = None
    selectedFunctions: Annotated[
        Optional[List[SelectedFunction]],
        Field(
            description="List of functions to be called by the model, refer to OpenAI schema for more details"
        ),
    ] = None
    functionCallParams: Annotated[
        Optional[FunctionCallParams],
        Field(description='Function calling mode - "none", "auto" or "force"'),
    ] = None
    forceFunction: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Force function-specific parameters"),
    ] = None


class PutConfigurationRequest(BaseModel):
    project: Annotated[
        str,
        Field(description="Name of the project to which this configuration belongs"),
    ]
    name: Annotated[str, Field(description="Name of the configuration")]
    provider: Annotated[
        str, Field(description='Name of the provider - "openai", "anthropic", etc.')
    ]
    parameters: Parameters1
    env: Annotated[
        Optional[List[EnvEnum]],
        Field(description="List of environments where the configuration is active"),
    ] = None
    type: Annotated[
        Optional[Type6],
        Field(
            description='Type of the configuration - "LLM" or "pipeline" - "LLM" by default'
        ),
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Details of user who created the configuration"),
    ] = None


class Parameters2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    call_type: Annotated[
        CallType, Field(description='Type of API calling - "chat" or "completion"')
    ]
    model: Annotated[str, Field(description="Model unique name")]
    hyperparameters: Annotated[
        Optional[Dict[str, Any]], Field(description="Model-specific hyperparameters")
    ] = None
    responseFormat: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description='Response format for the model with the key "type" and value "text" or "json_object"'
        ),
    ] = None
    selectedFunctions: Annotated[
        Optional[List[SelectedFunction]],
        Field(
            description="List of functions to be called by the model, refer to OpenAI schema for more details"
        ),
    ] = None
    functionCallParams: Annotated[
        Optional[FunctionCallParams],
        Field(description='Function calling mode - "none", "auto" or "force"'),
    ] = None
    forceFunction: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Force function-specific parameters"),
    ] = None


class PostConfigurationRequest(BaseModel):
    project: Annotated[
        str,
        Field(description="Name of the project to which this configuration belongs"),
    ]
    name: Annotated[str, Field(description="Name of the configuration")]
    provider: Annotated[
        str, Field(description='Name of the provider - "openai", "anthropic", etc.')
    ]
    parameters: Parameters2
    env: Annotated[
        Optional[List[EnvEnum]],
        Field(description="List of environments where the configuration is active"),
    ] = None
    user_properties: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Details of user who created the configuration"),
    ] = None


class CreateRunRequest(BaseModel):
    project: Annotated[
        str, Field(description="The UUID of the project this run is associated with")
    ]
    name: Annotated[str, Field(description="The name of the run to be displayed")]
    event_ids: Annotated[
        List[UUIDType],
        Field(
            description="The UUIDs of the sessions/events this run is associated with"
        ),
    ]
    dataset_id: Annotated[
        Optional[str],
        Field(description="The UUID of the dataset this run is associated with"),
    ] = None
    datapoint_ids: Annotated[
        Optional[List[str]],
        Field(
            description="The UUIDs of the datapoints from the original dataset this run is associated with"
        ),
    ] = None
    configuration: Annotated[
        Optional[Dict[str, Any]],
        Field(description="The configuration being used for this run"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]], Field(description="Additional metadata for the run")
    ] = None
    status: Annotated[Optional[Status], Field(description="The status of the run")] = (
        None
    )


class UpdateRunRequest(BaseModel):
    event_ids: Annotated[
        Optional[List[UUIDType]],
        Field(description="Additional sessions/events to associate with this run"),
    ] = None
    dataset_id: Annotated[
        Optional[str],
        Field(description="The UUID of the dataset this run is associated with"),
    ] = None
    datapoint_ids: Annotated[
        Optional[List[str]],
        Field(description="Additional datapoints to associate with this run"),
    ] = None
    configuration: Annotated[
        Optional[Dict[str, Any]],
        Field(description="The configuration being used for this run"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]], Field(description="Additional metadata for the run")
    ] = None
    name: Annotated[
        Optional[str], Field(description="The name of the run to be displayed")
    ] = None
    status: Optional[Status] = None


class DeleteRunResponse(BaseModel):
    id: Optional[UUIDType] = None
    deleted: Optional[bool] = None


class EvaluationRun(BaseModel):
    run_id: Annotated[Optional[UUIDType], Field(description="The UUID of the run")] = (
        None
    )
    project: Annotated[
        Optional[str],
        Field(description="The UUID of the project this run is associated with"),
    ] = None
    created_at: Annotated[
        Optional[AwareDatetime],
        Field(description="The date and time the run was created"),
    ] = None
    event_ids: Annotated[
        Optional[List[UUIDType]],
        Field(
            description="The UUIDs of the sessions/events this run is associated with"
        ),
    ] = None
    dataset_id: Annotated[
        Optional[str],
        Field(description="The UUID of the dataset this run is associated with"),
    ] = None
    datapoint_ids: Annotated[
        Optional[List[str]],
        Field(
            description="The UUIDs of the datapoints from the original dataset this run is associated with"
        ),
    ] = None
    results: Annotated[
        Optional[Dict[str, Any]],
        Field(
            description="The results of the evaluation (including pass/fails and metric aggregations)"
        ),
    ] = None
    configuration: Annotated[
        Optional[Dict[str, Any]],
        Field(description="The configuration being used for this run"),
    ] = None
    metadata: Annotated[
        Optional[Dict[str, Any]], Field(description="Additional metadata for the run")
    ] = None
    status: Optional[Status] = None
    name: Annotated[
        Optional[str], Field(description="The name of the run to be displayed")
    ] = None


class CreateRunResponse(BaseModel):
    evaluation: Annotated[
        Optional[EvaluationRun], Field(description="The evaluation run created")
    ] = None
    run_id: Annotated[
        Optional[UUIDType], Field(description="The UUID of the run created")
    ] = None


class GetRunsResponse(BaseModel):
    evaluations: Optional[List[EvaluationRun]] = None


class GetRunResponse(BaseModel):
    evaluation: Optional[EvaluationRun] = None
