"""Canonical re-export hub for generated Pydantic models.

This is the ONLY non-generated module that imports from
``honeyhive._generated.models``. Everything else (client.py, tests, the public
``honeyhive.models`` package) imports from here so we have a single seam
between auto-generated code and the rest of the SDK.

When the canonical spec drifts from what we want to expose publicly, add the
override here as a subclass or alias of the generated model — never modify
``_generated/`` (it gets clobbered on regeneration).
"""

from honeyhive._generated.models import (
    AddDatapointsResponse,
    AddDatapointsToDatasetRequest,
    BatchCreateDatapointsRequest,
    BatchCreateDatapointsResponse,
    ConfigurationItem,
    CreateConfigurationRequest,
    CreateConfigurationResponse,
    CreateDatapointRequest,
    CreateDatapointResponse,
    CreateDatasetRequest,
    CreateDatasetResponse,
    CreateMetricRequest,
    CreateMetricResponse,
    DatapointMapping,
    DeleteConfigurationResponse,
    DeleteDatapointParams,
    DeleteDatapointResponse,
    DeleteDatasetQuery,
    DeleteDatasetResponse,
    DeleteExperimentRunParams,
    DeleteExperimentRunResponse,
    DeleteMetricQuery,
    DeleteMetricResponse,
    Event,
    GetConfigurationsQuery,
    GetConfigurationsResponse,
    GetDatapointParams,
    GetDatapointResponse,
    GetDatapointsQuery,
    GetDatapointsResponse,
    GetDatasetsResponse,
    GetEventsQuery,
    GetEventsResponse,
    GetEventsSchemaQuery,
    GetEventsSchemaResponse,
    GetExperimentRunCompareEventsQuery,
    GetExperimentRunCompareParams,
    GetExperimentRunCompareQuery,
    GetExperimentRunMetricsQuery,
    GetExperimentRunParams,
    GetExperimentRunResponse,
    GetExperimentRunResultQuery,
    GetExperimentRunsQuery,
    GetExperimentRunsResponse,
    GetMetricsQuery,
    GetMetricsResponse,
    LegacyEvent,
    LegacyUpdateDatasetRequest,
    MetricItem,
    Pagination,
    PostEventBatchRequest,
    PostEventBatchResponse,
    PostEventRequest,
    PostEventResponse,
    PostExperimentRunRequest,
    PostExperimentRunResponse,
    PostSessionRequest,
    PostSessionStartResponse,
    PutExperimentRunRequest,
    PutExperimentRunResponse,
    RemoveDatapointFromDatasetParams,
    RemoveDatapointResponse,
    RunMetricRequest,
    RunMetricResponse,
    StartSessionRequest,
    TODOSchema,
    UpdateConfigurationRequest,
    UpdateConfigurationResponse,
    UpdateDatapointParams,
    UpdateDatapointRequest,
    UpdateDatapointResponse,
    UpdateDatasetResponse,
    UpdateEventRequest,
    UpdateMetricRequest,
    UpdateMetricResponse,
)


# Public name for dataset update requests. The canonical spec renamed this
# to the new PUT /datasets/{dataset_id} shape (no dataset_id in the body),
# but the Python SDK still calls the legacy PUT /datasets endpoint to avoid
# breaking customers.
class UpdateDatasetRequest(LegacyUpdateDatasetRequest):
    pass


# Back-compat aliases for the GET /runs/schema → GET /events/schema rename
# (#3440). The generated symbols moved to GetEventsSchema*; these keep the
# old public names importable from honeyhive.models.
GetExperimentRunsSchemaQuery = GetEventsSchemaQuery
GetExperimentRunsSchemaResponse = GetEventsSchemaResponse


# Note: models prefixed with Legacy are intentionally not re-exported — they are
# implementation details of the aliases above
__all__ = [
    "AddDatapointsResponse",
    "AddDatapointsToDatasetRequest",
    "BatchCreateDatapointsRequest",
    "BatchCreateDatapointsResponse",
    "ConfigurationItem",
    "CreateConfigurationRequest",
    "CreateConfigurationResponse",
    "CreateDatapointRequest",
    "CreateDatapointResponse",
    "CreateDatasetRequest",
    "CreateDatasetResponse",
    "CreateMetricRequest",
    "CreateMetricResponse",
    "DatapointMapping",
    "DeleteConfigurationResponse",
    "DeleteDatapointParams",
    "DeleteDatapointResponse",
    "DeleteDatasetQuery",
    "DeleteDatasetResponse",
    "DeleteExperimentRunParams",
    "DeleteExperimentRunResponse",
    "DeleteMetricQuery",
    "DeleteMetricResponse",
    "Event",
    "GetConfigurationsQuery",
    "GetConfigurationsResponse",
    "GetDatapointParams",
    "GetDatapointResponse",
    "GetDatapointsQuery",
    "GetDatapointsResponse",
    "GetDatasetsResponse",
    "GetEventsQuery",
    "GetEventsResponse",
    "GetEventsSchemaQuery",
    "GetEventsSchemaResponse",
    "GetExperimentRunCompareEventsQuery",
    "GetExperimentRunCompareParams",
    "GetExperimentRunCompareQuery",
    "GetExperimentRunMetricsQuery",
    "GetExperimentRunParams",
    "GetExperimentRunResponse",
    "GetExperimentRunResultQuery",
    "GetExperimentRunsQuery",
    "GetExperimentRunsResponse",
    "GetExperimentRunsSchemaQuery",
    "GetExperimentRunsSchemaResponse",
    "GetMetricsQuery",
    "GetMetricsResponse",
    "LegacyEvent",
    "MetricItem",
    "Pagination",
    "PostEventBatchRequest",
    "PostEventBatchResponse",
    "PostEventRequest",
    "PostEventResponse",
    "PostExperimentRunRequest",
    "PostExperimentRunResponse",
    "PostSessionRequest",
    "PostSessionStartResponse",
    "PutExperimentRunRequest",
    "PutExperimentRunResponse",
    "RemoveDatapointFromDatasetParams",
    "RemoveDatapointResponse",
    "RunMetricRequest",
    "RunMetricResponse",
    "StartSessionRequest",
    "TODOSchema",
    "UpdateConfigurationRequest",
    "UpdateConfigurationResponse",
    "UpdateDatapointParams",
    "UpdateDatapointRequest",
    "UpdateDatapointResponse",
    "UpdateDatasetRequest",
    "UpdateDatasetResponse",
    "UpdateEventRequest",
    "UpdateMetricRequest",
    "UpdateMetricResponse",
]
