"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import dataset as components_dataset
from typing import List, Optional


@dataclasses.dataclass
class GetDatasetsRequest:
    task: str = dataclasses.field(metadata={'query_param': { 'field_name': 'task', 'style': 'form', 'explode': True }})
    dataset_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'dataset_id', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetDatasetsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    datasets: Optional[List[components_dataset.Dataset]] = dataclasses.field(default=None)
    r"""A list of datasets"""
    

