"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import testcaseupdate as components_testcaseupdate


@dataclasses.dataclass
class PutTestcasesRequest:
    testcase_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'testcase_id', 'style': 'form', 'explode': True }})
    r"""The ID of the testcase to update"""
    testcase_update: components_testcaseupdate.TestcaseUpdate = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class PutTestcasesResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    

