workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: openapi.yaml
targets:
    honeyhive:
        target: python
        source: my-source
        publish:
            pypi:
                token: $pypi_token
