workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/honey-hive/honeyhive-jxo/my-source
targets:
    honeyhive:
        target: python
        source: my-source
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/honey-hive/honeyhive-jxo/my-source-python-code-samples
