#!/usr/bin/env python3
"""
Generate v0 Models and Client from OpenAPI Specification

This script regenerates the Pydantic models from the OpenAPI specification
using datamodel-codegen. This is the lightweight, hand-written API client
approach where models are auto-generated but the client code is maintained
manually.

Usage:
    python scripts/generate_v0_models.py

The generated models are written to:
    src/honeyhive/models/generated.py

Post-processing:
    After generation, the script applies customizations for backwards
    compatibility (e.g., adding __str__ to UUIDType for proper string conversion).
"""

import re
import subprocess
import sys
from pathlib import Path

# Get the repo root directory
REPO_ROOT = Path(__file__).parent.parent
OPENAPI_SPEC = REPO_ROOT / "openapi" / "v0.yaml"
OUTPUT_FILE = REPO_ROOT / "src" / "honeyhive" / "_v0" / "models" / "generated.py"


def post_process_generated_file(filepath: Path) -> bool:
    """
    Apply post-processing customizations to the generated models.

    This ensures backwards compatibility by adding methods that users
    expect but aren't generated by datamodel-codegen.

    Returns True if successful, False otherwise.
    """
    print("🔧 Applying post-processing customizations...")

    try:
        content = filepath.read_text()

        # Add __str__ and __repr__ methods to UUIDType for backwards compatibility
        # Users expect str(uuid_type_instance) and repr(uuid_type_instance) to work intuitively
        old_uuid_type = "class UUIDType(RootModel[UUID]):\n    root: UUID"
        new_uuid_type = '''class UUIDType(RootModel[UUID]):
    """UUID wrapper type with string conversion support."""

    root: UUID

    def __str__(self) -> str:
        """Return string representation of the UUID for backwards compatibility."""
        return str(self.root)

    def __repr__(self) -> str:
        """Return repr showing the UUID value directly."""
        return f"UUIDType({self.root})"'''

        if old_uuid_type in content:
            content = content.replace(old_uuid_type, new_uuid_type)
            print("  ✓ Added __str__ method to UUIDType")
        else:
            print("  ⚠ UUIDType pattern not found (may already be customized)")

        filepath.write_text(content)
        return True

    except Exception as e:
        print(f"  ❌ Post-processing failed: {e}")
        return False


def main():
    """Generate models from OpenAPI specification."""
    print("🚀 Generating v0 Models (datamodel-codegen)")
    print("=" * 50)

    # Validate that the OpenAPI spec exists
    if not OPENAPI_SPEC.exists():
        print(f"❌ OpenAPI spec not found: {OPENAPI_SPEC}")
        return 1

    print(f"📖 OpenAPI Spec: {OPENAPI_SPEC}")
    print(f"📝 Output File: {OUTPUT_FILE}")
    print()

    # Run datamodel-codegen
    cmd = [
        "datamodel-codegen",
        "--input",
        str(OPENAPI_SPEC),
        "--output",
        str(OUTPUT_FILE),
        "--target-python-version",
        "3.11",
        "--output-model-type",
        "pydantic_v2.BaseModel",
        # Note: --use-annotated flag removed to match original generation style
        # Original used Field(..., description=) not Annotated[type, Field(description=)]
    ]

    print(f"Running: {' '.join(cmd)}")
    print()

    try:
        result = subprocess.run(cmd, check=True)
        if result.returncode == 0:
            print()
            print("✅ Model generation successful!")
            print()

            # Apply post-processing customizations
            if not post_process_generated_file(OUTPUT_FILE):
                print("❌ Post-processing failed")
                return 1

            print()
            print("📁 Generated Files:")
            print(f"  • {OUTPUT_FILE.relative_to(REPO_ROOT)}")
            print()
            print("💡 Next Steps:")
            print("  1. Review the generated models for correctness")
            print("  2. Run tests to ensure compatibility: make test")
            print(
                "  3. Commit the changes: git add src/honeyhive/models/generated.py && git commit -m 'feat(models): regenerate from updated OpenAPI spec'"
            )
            print()
            return 0
        else:
            print(f"❌ Model generation failed with return code {result.returncode}")
            return 1

    except FileNotFoundError:
        print("❌ datamodel-codegen not found!")
        print()
        print("Please install the datamodel-code-generator package:")
        print("  pip install 'datamodel-code-generator>=0.20.0'")
        print()
        print("Or install the SDK with dev dependencies:")
        print("  pip install -e '.[dev]'")
        return 1
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running datamodel-codegen: {e}")
        return 1
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
