name: HoneyHive Evaluation

on:
  pull_request:
    branches:
      - "main"

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Run HoneyHive Evaluation
      id: evaluate
      uses: honeyhiveai/honeyhive-eval@main
      with:
        runtime: python
        runId: 'a1ac2cb9-2034-469b-9149-3e6452120201'
        project: ${{ secrets.HH_PROJECT }}
        aggregateFunction: average
        root: '.'
        apiKey: ${{ secrets.HH_API_KEY }}
        openaiApiKey: ${{ secrets.OPENAI_API_KEY }}

    - name: Display Evaluation Results
      run: |
        echo "Evaluation Status: ${{ steps.evaluate.outputs.status }}"
        echo "Success: ${{ steps.evaluate.outputs.success }}"
        echo "Passed Datapoints: ${{ steps.evaluate.outputs.passed }}"
        echo "Failed Datapoints: ${{ steps.evaluate.outputs.failed }}"
        echo "Metrics: ${{ steps.evaluate.outputs.metrics }}"
        echo "Datapoints: ${{ steps.evaluate.outputs.datapoints }}"