name: Run Tests

on:
  repository_dispatch:
    types: [trigger-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Validate Payload
        run: |
          if [ "${{ github.event.client_payload.secret }}" != "${{ secrets.EXPECTED_SECRET }}" ]; then
            echo "Invalid secret"
            exit 1
          fi

      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f tests/Dockerfile . -t my-test
      - name: Run Docker image
        run: |
          docker run -e HH_API_KEY="${{ secrets.HH_API_KEY }}" \
                     -e HH_API_URL="${{ github.event.client_payload.api_url }}" \
                     -e HH_PROJECT="${{ secrets.HH_PROJECT }}" \
                     -e HH_PROJECT_ID="${{ secrets.HH_PROJECT_ID }}" \
                     -e HH_DATASET="${{ secrets.HH_DATASET }}" \
                     -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                     -e SERP_API_KEY="${{ secrets.SERP_API_KEY }}" \
                     -e COHERE_API_KEY="${{ secrets.COHERE_API_KEY }}" \
                     -t my-test
